apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petclinic.fullname" . }}
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "petclinic.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "petclinic.selectorLabels" . | nindent 8 }}

    spec:
      serviceAccountName: petclinic
      containers:
        - name: petclinic

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ include "petclinic.fullname" . }}-postgresql:5432/{{ .Values.postgres.database }}

            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgresql.auth.username | quote }}

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  {{ include "petclinic.fullname" . }}-postgresql
                  key: password

          envFrom:
            - configMapRef:
                name: {{ include "petclinic.fullname" . }}-config

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"

            limits:
              cpu: "1"
              memory: "1Gi"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
