replicaCount: 4

image:
  repository: affaana/petclinic
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080

config:
  springProfile: default
  appEnv: kubernetes

postgresql:
  auth:
    username: petclinic
    password: petclinic123
    database: petclinic
autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70

postgres:
  image:
    repository: postgres
    tag: "16"
  database: petclinic
  username: petclinic
  password: petclinic123
  storage:
    accessMode: ReadWriteOnce
    size: 1Gi
ingress:
  className: nginx
  host: petclinic.local
